source 'http://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'page-object', '1.1.0'
gem 'faker'
gem 'require_all'
gem 'syntax'
gem 'headless'
gem 'rake'
gem 'sinatra'
gem 'premailer'
gem 'nokogiri'
gem 'activesupport'
gem 'tzinfo'
gem 'pdf-reader'
gem 'parallel_tests'
