source 'http://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'page-object'
gem 'data_magic'
gem 'faker'
gem 'fig_newton'
gem 'require_all'
gem 'syntax'
gem 'headless'
gem 'rake'
gem 'sinatra'
gem 'premailer'
gem 'nokogiri'
gem 'activesupport'
gem 'tzinfo'
gem 'pdf-reader'