base_url: http://dev188.sure.vine/

# Users
user1_irlname: Stephanie Keelson
user1_surname: keelson
user1_uname: stephaniek@surevine
user1_uname_en: stephaniek@surevine
user1_pswd: "%RI6dpNoU#hoyPh%6dBe"
user1_id: stephaniek%40surevine

user2_irlname: Simon Whitson
user2_surname: whitson
user2_uname: simonwhi@surevine
user2_uname_en: simonwhi@surevine
user2_pswd:  "CJ0b^7vDiz486EWrp%Ye"
user2_id:    simonwhi%40surevine

user3_irlname: Normal User2
user3_surname: user2
user3_uname: normal2
user3_uname_en: normal2
user3_pswd:  password
user3_id:    2003

adminuser_irlname: Admin
adminuser_uname: admin
adminuser_uname_en: admin
adminuser_pswd:  admin

# Groups
custom_group: testing
secret_group: user2-secret
custom_space: TEST-SPACE
