base_url:           http://dev188.sure.vine/

# Users
user1_irlname:      <%= ENV['user1_irlname'] %>
user1_surname:      <%= ENV['user1_surname'] %>
user1_uname:        <%= ENV['user1_uname'] %>
user1_uname_en:     <%= ENV['user1_uname_en'] %>
user1_pswd:         <%= ENV['user1_pswd'] %>
user1_id:           <%= ENV['user1_id'] %>

user2_irlname:      Simon Whitson
user2_surname:      whitson
user2_uname:        simonwhi@surevine
user2_uname_en:     simonwhi@surevine
user2_pswd:         "CJ0b^7vDiz486EWrp%Ye"
user2_id:           simonwhi%40surevine

user3_irlname:      Normal User2
user3_surname:      user2
user3_uname:        normal2
user3_uname_en:     normal2
user3_pswd:         password
user3_id:           2003

adminuser_irlname:  Barry Holmes
adminuser_uname:    barryh@surevine
adminuser_uname_en: barryh@surevine
adminuser_pswd:     "*3mQOCCXkGe!Gz7@Q2CN"

# Groups
custom_group:       testing
secret_group:       secret-test-group
custom_space:       test-space
