base_url:           http://dev188.sure.vine/

# CE Participant A
user1_irlname:      ~ENV['user1_irlname']
user1_surname:      ~ENV['user1_surname']
user1_uname:        ~ENV['user1_uname']
user1_uname_en:     ~ENV['user1_uname_en']
user1_pswd:         ~ENV['user1_pswd']
user1_id:           ~ENV['user1_id']

# CE Participant B
user2_irlname:      ~ENV['user2_irlname']
user2_surname:      ~ENV['user2_surname']
user2_uname:        ~ENV['user2_uname']
user2_uname_en:     ~ENV['user2_uname_en']
user2_pswd:         ~ENV['user2_pswd']
user2_id:           ~ENV['user2_id']

# Additional user - not entirely sure how much this gets used. ~TD
user3_irlname:      ~ENV['user3_irlname']
user3_surname:      ~ENV['user3_surname']
user3_uname:        ~ENV['user3_uname']
user3_uname_en:     ~ENV['user3_uname_en']
user3_pswd:         ~ENV['user3_pswd']
user3_id:           ~ENV['user3_id']

# Admin User
adminuser_irlname:  ~ENV['adminuser_irlname']
adminuser_uname:    ~ENV['adminuser_uname']
adminuser_uname_en: ~ENV['adminuser_uname_en']
adminuser_pswd:     ~ENV['adminuser_pswd']

# Places used for content
custom_group:       ~ENV['custom_group']
secret_group:       ~ENV['secret_group']
custom_space:       ~ENV['custom_space']
