base_url: http://10.66.2.114:8080/

# Users
user1_irlname: Matt Willshire
user1_surname: willshire
user1_uname: willshiremd@surevine
user1_uname_en: willshiremd@surevine
user1_pswd: tashcup
user1_id: willshiremd%40surevine

user2_irlname: Tim Durden
user2_surname: durden
user2_uname: durdentj@surevine
user2_uname_en: durdentj@surevine
user2_pswd:  Pa55word
user2_id:    2005

user3_irlname: Normal User2
user3_surname: user2
user3_uname: normal2
user3_uname_en: normal2
user3_pswd:  password
user3_id:    2003

adminuser_irlname: Admin
adminuser_uname: admin
adminuser_uname_en: admin
adminuser_pswd:  admin

# Groups
custom_group: testing
secret_group: user2-secret
custom_space: TEST-SPACE